"""
simple_model_config.py
****
config for charades dataset
"""
from yacs.config import CfgNode as CN
_C = CN()
_C.EXP_NAME = "SimpleModel-verbpos"
#_C.EXP_NAME = "Debug"

# training options
_C.DATASET = CN()
_C.DATASET.NAME = "Charades"
_C.DATASET.SHOW_TOP_VOCAB = 1
_C.DATASET.BATCH_SIZE = 100
_C.DATASET.MAX_LENGTH = 15
_C.DATASET.NUM_SEGMENT = 128
_C.DATASET.DATA_PATH = "/home/data/anet"
_C.DATASET.TRAIN_ANNO_PATH = "annotations/charades_sta_train.json"
_C.DATASET.TEST_ANNO_PATH = "annotations/charades_sta_test.json"
_C.DATASET.VID_PATH = ""

# model options
_C.MODEL = CN()
_C.MODEL.QUERY = CN()
_C.MODEL.QUERY.EMB_IDIM = -1
_C.MODEL.QUERY.EMB_ODIM = 300
_C.MODEL.QUERY.GRU_HDIM = 256
_C.MODEL.VIDEO = CN()
_C.MODEL.VIDEO.IDIM = 1024
_C.MODEL.VIDEO.GRU_HDIM = 256
_C.MODEL.FUSION = CN()
_C.MODEL.FUSION.EMB_DIM = 256
_C.MODEL.FUSION.NUM_HEAD = 8
_C.MODEL.FUSION.NUM_LAYERS = 3
_C.MODEL.FUSION.CONVBNRELU = CN()
_C.MODEL.FUSION.CONVBNRELU.KERNEL_SIZE = 3
_C.MODEL.FUSION.CONVBNRELU.PADDING = 1
_C.MODEL.NONLOCAL = CN()
_C.MODEL.NONLOCAL.NUM_LAYERS = 2
_C.MODEL.NONLOCAL.NUM_HEAD = 4
_C.MODEL.NONLOCAL.USE_BIAS = True
_C.MODEL.NONLOCAL.DROPOUT = 0.0

# training options
_C.TRAIN = CN()
_C.TRAIN.LR = 0.0001
_C.TRAIN.NUM_EPOCH = 300
_C.TRAIN.BATCH_SIZE = 100
_C.TRAIN.NUM_WORKERS = 4
_C.TRAIN.IOU_THRESH = [0.3,0.5,0.7]
